service: go-gateway
#app: your-app-name
#tenant: your-tenant-name

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  # deploymentBucket:
  #   name: go-serverless

# package:
#   exclude:
#     - ./**
#   include:
#     - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - http:
          path: /{proxy+}
          method: any
    reservedConcurrency: 500